spring.application.name=Collaborative_Whiteboard_18
server.port=8080

spring.data.mongodb.uri=mongodb+srv://arjunnagar486_db_user:OSKvpzz4VNEdJimD@cluster0.uvonpvr.mongodb.net/?appName=Cluster0


# ?? File Upload Limits (for export endpoint) ?????????????????????????????????
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ?? Logging (optional, helpful during dev) ???????????????????????????????????
logging.level.org.springframework.web.socket=DEBUG
logging.level.com.example.collaborative_whiteboard_18=DEBUG