server.port=8080

spring.data.mongodb.uri=mongodb+srv://arjunnagar486_db_user:OSKvpzz4VNEdJimD@cluster0.uvonpvr.mongodb.net/?appName=Cluster0
# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Async timeout (keep this)
spring.mvc.async.request-timeout=60000